[pyprland]
plugins = [
  "scratchpads"
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
position = "17% 6%"
size = "65% 60%"
offset = "200%"
lazy = true

[scratchpads.music]
animation = "fromBottom"
command = "kitty --class kitty-pulsemixer -e pulsemixer"
class = "kitty-pulsemixer"
size = "50% 20%"
offset = "200%"
lazy = true

[scratchpads.taskbar]
animation = "fromLeft"
command = "kitty --class kitty-taskbar -e htop"
class = "kitty-taskbar"
size = "30% 80%"
offset = "200%"
lazy = true

[scratchpads.ncmpcpp]
animation = "fromTop"
command = "kitty --class scratch-music --title scratch-music -e ncmpcpp"
class = "scratch-music"
size = "40% 30%"
position = "30% 3%"
offset = "200%"
lazy = true

